require "fileutils"
require "yaml"

module OutlawSkills
  module Targets
    # Emits `dist/copilot/` per docs/research/copilot-plugin-format.md.
    #
    # Surfaces (verified against current VS Code Copilot docs, 2026-05-26):
    #   - .github/copilot-instructions.md  (always-on digest, plain markdown)
    #   - .github/agents/*.agent.md        (one per Claude Code agent; custom-agents
    #                                       surface that superseded .chatmode.md in
    #                                       VS Code 1.106)
    #   - .github/prompts/*.prompt.md      (one per skill; `agent:` frontmatter field)
    #
    # Surfaces deferred (no current source content needs them):
    #   - .github/instructions/*.instructions.md  (would require a `scope:` / `applyTo:`
    #     field in canonical skill frontmatter; revisit when first skill needs it)
    class Copilot
      NAME = "copilot".freeze

      # Claude-Code-tool → Copilot-tool identifier mapping. Conservative subset,
      # verified against current VS Code Copilot Chat tool identifiers.
      TOOL_TRANSLATIONS = {
        "Read"       => "codebase",
        "Grep"       => "search",
        "Glob"       => "search",
        "Bash"       => "runCommands",
        "Edit"       => "editFiles",
        "Write"      => "editFiles",
        "MultiEdit"  => "editFiles",
        "WebFetch"   => "fetch",
        "WebSearch"  => "githubRepo"
      }.freeze

      def initialize(builder)
        @builder = builder
        @dist_dir = File.join(builder.dist_root, "copilot")
        @gh_dir = File.join(@dist_dir, ".github")
      end

      def build
        FileUtils.rm_rf(@dist_dir)
        FileUtils.mkdir_p(@gh_dir)
        skills = @builder.skills_for(NAME)
        agents = @builder.agents_for(NAME)
        write_agents(agents)
        write_prompts(skills)
        write_top_level_instructions(skills, agents)
        write_readme
      end

      private

      def write_top_level_instructions(skills, agents)
        lines = []
        lines << "<!-- Generated by outlaw-skills v#{@builder.version}. Do not edit by hand. -->"
        lines << ""
        lines << "# outlaw-skills"
        lines << ""
        lines << "Cross-tool layer of curated coding-agent guidance. The content under this `.github/` directory is generated from canonical source in the outlaw-skills repo."
        lines << ""
        unless skills.empty?
          lines << "## Available prompts"
          lines << ""
          lines << "Invoke any of these in Copilot Chat with `/<name>`:"
          lines << ""
          skills.each do |s|
            desc = s.frontmatter["description"].to_s.lines.first.to_s.strip
            lines << "- **/#{s.name}** — #{desc}"
          end
          lines << ""
        end
        unless agents.empty?
          lines << "## Available agents"
          lines << ""
          lines << "Select from the Copilot Chat agent picker:"
          lines << ""
          agents.each do |a|
            desc = a.frontmatter["description"].to_s.lines.first.to_s.strip
            lines << "- **#{a.name}** — #{desc}"
          end
          lines << ""
        end
        File.write(File.join(@gh_dir, "copilot-instructions.md"), lines.join("\n"))
      end

      def write_agents(agents)
        return if agents.empty?
        dest = File.join(@gh_dir, "agents")
        FileUtils.mkdir_p(dest)
        agents.each do |agent|
          out_path = File.join(dest, "#{agent.name}.agent.md")
          File.write(out_path, build_agent_content(agent))
        end
      end

      def build_agent_content(agent)
        fm, body = Frontmatter.parse(File.read(agent.path, encoding: "UTF-8"), source_path: agent.path)
        out_fm = {}
        out_fm["description"] = fm["description"] if fm["description"]
        translated_tools = translate_tools(fm["tools"])
        out_fm["tools"] = translated_tools if translated_tools && !translated_tools.empty?
        translated_model = translate_model(fm["model"])
        out_fm["model"] = translated_model if translated_model

        header = "<!-- Generated by outlaw-skills v#{@builder.version}. Source: src/agents/#{File.basename(agent.path)} -->\n"
        serialize_with_frontmatter(out_fm, header + body.lstrip)
      end

      def write_prompts(skills)
        return if skills.empty?
        dest = File.join(@gh_dir, "prompts")
        FileUtils.mkdir_p(dest)
        skills.each do |skill|
          out_path = File.join(dest, "#{skill.name}.prompt.md")
          File.write(out_path, build_prompt_content(skill))
        end
      end

      def build_prompt_content(skill)
        fm, body = Frontmatter.parse(File.read(skill.skill_md_path, encoding: "UTF-8"), source_path: skill.skill_md_path)
        out_fm = {}
        # `agent:` selects which agent runs the prompt (ask | agent | plan | <custom>).
        out_fm["agent"] = "agent"
        out_fm["description"] = fm["description"] if fm["description"]

        header = "<!-- Generated by outlaw-skills v#{@builder.version}. Source: src/skills/#{skill.name}/SKILL.md -->\n"
        serialize_with_frontmatter(out_fm, header + body.lstrip)
      end

      def write_readme
        File.write(File.join(@dist_dir, "README.md"), <<~MD)
          # outlaw-skills — Copilot distribution

          Generated by `bin/build copilot`. Do not edit by hand — changes will be overwritten.

          ## Install

          Two options:

          1. **Repo-scoped install** — copy `.github/` into your repo root:
             ```
             cp -r dist/copilot/.github /path/to/your/repo/
             ```
             Skills become available as `/name` slash commands; agents appear in the
             Copilot Chat agent picker; the always-on digest in `.github/copilot-instructions.md`
             is auto-loaded into every Copilot Chat request in that workspace.

          2. **User-scoped install (VS Code, macOS)** — symlink the generated files into
             your VS Code user profile so they're available in every workspace:
             ```
             ln -sfn "$PWD"/dist/copilot/.github/prompts/*.prompt.md \\
               "$HOME/Library/Application Support/Code/User/prompts/"
             ln -sfn "$PWD"/dist/copilot/.github/agents/*.agent.md "$HOME/.copilot/agents/"
             ```
             Paths vary by OS and VS Code profile; see current VS Code docs
             (`chat.promptFilesLocations`, `chat.agentFilesLocations`).

          ## Source

          Canonical source lives in the outlaw-skills repo under `src/`. The build
          script (`bin/build copilot`) is the only thing that should write to this
          directory.

          Generated from outlaw-skills v#{@builder.version}.
        MD
      end

      def translate_tools(claude_tools)
        return nil if claude_tools.nil?
        list = case claude_tools
               when String then claude_tools.split(",").map(&:strip)
               when Array  then claude_tools
               else return nil
               end
        translated = list.filter_map { |t| TOOL_TRANSLATIONS[t.to_s] }.uniq
        translated.empty? ? nil : translated
      end

      def translate_model(claude_model)
        return nil if claude_model.nil? || claude_model.to_s == "inherit"
        # Pass through the canonical model identifier. Copilot accepts a supported
        # model id/display name; an unrecognized value is ignored and the user picks.
        claude_model.to_s
      end

      def serialize_with_frontmatter(fm, body)
        if fm.empty?
          body.start_with?("\n") ? body : "\n#{body}"
        else
          yaml = YAML.dump(fm).sub(/\A---\n/, "").chomp.chomp("\n")
          "---\n#{yaml}\n---\n#{body}"
        end
      end
    end
  end
end
